### ISSUE TITLE
Support: xedixSetup.exe fails to run on app version v4.1.alpha.7

### ISSUE THREAD

**Issue by divyanshudhruv** [mostypc123/XediX#36]
## 📄 Question or Issue  
When I attempt to run the xedixSetup.exe file on my system, I receive the following error message:
"This app can't run on your PC. To find a version for your PC, check with the software publisher."

## 🛠️ Steps Taken  
1. Download the xedixSetup.exe file.
2. Double-click the file to execute it.
3. The error message appears immediately.

--- 
1.  Checked the docs, no possible solution.
2.  Searched the issues, no related issue found.
3.  Tried debugging the code, but found no possible area for the error.

---

## 🔍 Context or Details  

- **Environment**: (e.g., OS, Python version, app version)  
> Windows 11 (64-bit), Python 3.13.1, App Version v4.1.alpha.7  (v4.0.alpha.2)
- **Logs or Error Messages**: (If applicable, include logs or errors here)  
> No logs 
- **Screenshots**: (If applicable, include screenshots here)  
> ![image](https://github.com/user-attachments/assets/a9be8ae9-9402-409b-8a9a-07c11a8512e9)
 

## 🔗 Additional Context  
Administrator Privileges: Confirmed (tried running as administrator)

**Comment by mostypc123** [comment]
that might work, but if not, feel free to ask again

**Comment by mostypc123** [comment]
![installationnotice](https://github.com/user-attachments/assets/55de25c5-9582-416a-97c3-a56a29c3d618)

> [!NOTE]
>  also its v4.1.alpha.5, 7 doesn't have the executable but because you ran the setup it's probably just 5.

**Comment by divyanshudhruv** [comment]
Yep, I noticed it a bit late 😅. But I figured out how to run the program 👍
