### ISSUE TITLE
 Feature Request: Enhancements to Improve User Experience in the Python Code Editor

### ISSUE THREAD

**Issue by Dev-Hassaan** [mostypc123/XediX#42]
---

# Feature Request: Enhancements to Improve User Experience in the Python Code Editor

## Existing Features
The current version of the editor includes the following features:

### File Menu
- Save
- Run Code
- Run Pyline
- Exit

### Edit Menu
- Cut
- Copy
- Paste
- Find and Replace
- Jump to Line

### Tools Menu
- Tools
- Deployment Tools
- Customize
- Git

### Help Menu
- Homepage
- About
- Docs

---

## Identified Problems
While the editor offers some useful features, there are several problematic aspects that impact usability:

1. **Confusing Features**:
   - "Run Pyline" is unclear and lacks explanation or documentation.
   - The "Tools" option is vague and doesn't specify its purpose.
   - "Deployment Tools" is ambiguous and seems unrelated to the primary function of the editor.

2. **User Experience Issues**:
   - Files can be added, but there is no way to delete or edit them.
   - The editor allows typing, but there is no blinking cursor or support for arrow key navigation.
   - New files can be opened but cannot be closed.
   - The editor crashes when a file with an unsupported extension is added.

---

## Recommendations for Improvement
To provide a better user experience and align with modern coding standards, the following changes are recommended:

1. **Basic File Management**:
   - Add options to delete, rename, and edit files.
   - Allow users to open folders or files from other directories.
   - Support reordering, searching, and closing files.

2. **Enhance Coding Workflow**:
   - Introduce a visible, blinking cursor in the editor.
   - Enable navigation with arrow keys and shortcuts for efficient coding.
   - Ensure the editor gracefully handles unsupported file extensions.

3. **Improved Usability**:
   - Automatically add a `.py` extension when users create a file without specifying an extension.
   - Provide a clear indicator for unsaved changes and include an auto-save feature.

4. **Customization Options**:
   - Allow users to select themes for a more personalized and visually appealing experience.
   - Take inspiration from IDEs like Visual Studio Code for features and extensibility.

---

## Feature Requests
To address the above issues, I propose adding the following features:

1. **File Management**:
   - Add, delete, rename, and reorder files.
   - Open files or folders from other directories.
   - Support file diff and search functionalities.

2. **Editor Navigation**:
   - Add a visible cursor and enable navigation with arrow keys.
   - Provide shortcuts for better productivity.

3. **Customization**:
   - Include pre-made themes for better aesthetics.

4. **File State Management**:
   - Show an indicator for unsaved changes.
   - Implement auto-save to reduce the risk of losing work.

---

**Comment by mostypc123** [comment]
very good feature request but themes are already there check src/theme.xcfg

**Comment by Dev-Hassaan** [comment]
I am talking about this, look at the vs code theme switching 

<img src="https://code.visualstudio.com/assets/docs/getstarted/themes/themes_hero.gif">

**Comment by mostypc123** [comment]
yeah ik thats just a solution made in a hour will try to make it like that
